main:
  - name: Aktuelles
    pageRef: /news
    weight: 10
  - name: Über mich
    pageRef: /about-me
    weight: 20
  - name: Politik
    pageRef: /politics
    weight: 30
  - name: Kontakt
    pageRef: /contact
    weight: 40

footer:
  - name: Impressum
    pageRef: /legal-notice
    weight: 10
  - name: Datenschutzerklärung
    pageRef: /privacy-statement
    weight: 20
