main:
  - name: Über mich
    url: /ueber-mich
    weight: 10
  - name: Politik
    url: /politik
    weight: 20
  - name: Beiträge
    url: /blog
    weight: 30
  - name: Kontakt
    url: /kontakt
    weight: 40

footer:
  - name: Impressum
    url: /impressum
    weight: 10
  - name: Datenschutzerklärung
    url: /datenschutzerklaerung
    weight: 20
