colorScheme: congo
logo: img/logo.svg

article:
  showAuthor: false

homepage:
  layout: hero
  showRecent: true
  mainSections: ["blog"]

header:
  layout: fixed-fill-blur

footer:
  showCopyright: false
  showThemeAttribution: false
